# This is a basic workflow to help you get started with Actions

name: hello

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo IS java installed ?
          java -version
          echo List all files ?
          ls -la
          echo Present path ?
          pwd
          echo Present ls .git ?
          ls .git/
          echo Present ls .git/branches ?
          ls .git/branches
          echo Present ls .github/ ?
          ls .github/
          echo Present ls .github/workflows ?
          ls .github/workflows/
          cd .github/workflows/
          pwd
          export OICURL=https://oic99411728-ocuocictrng30-ld.integration.ocp.oraclecloud.com:443
          export OICUser=99411728-ora006
          export OICPassword=Welcome@123
          export OICProject=HELL2|01.00.0000
          export URL=$OICURL/ic/api/integration/v1/integrations/$OICProject/archive
          echo $URL
